// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyrnnbqzfsdreyjhkhig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cm5uYnF6ZnNkcmV5amhraGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzMxMzcsImV4cCI6MjA1OTcwOTEzN30.xVQTGurZUt0C71GIGeQHu4d46j4eW1ZKRjGW4FnyQmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);